#Installations

In [1]:
pip install apyori

Requirement already satisfied: apyori in /usr/local/lib/python3.7/dist-packages (1.1.2)

#Imports

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
color = sns.color_palette()
from apyori import apriori

#read clean dataset

In [3]:
clean_df= pd.read_csv('/content/drive/MyDrive/Capstone Project/Data Files/Bank Loan Default_CleanBaseLine_v3.0.csv')

In [4]:
clean_df.shape

(119145, 19)

In [5]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119145 entries, 0 to 119144
Data columns (total 19 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   member_id        119145 non-null  int64
 1   loan_amnt        119145 non-null  int64
 2   funded_amnt      119145 non-null  int64
 3   funded_amnt_inv  119145 non-null  float64
 4   term             119145 non-null  object
 5   int_rate         119145 non-null  float64
 6   installment      119145 non-null  float64
 7   grade            119145 non-null  object
 8   emp_length       119145 non-null  int64
 9   home_ownership   119145 non-null  object
 10  annual_inc       119145 non-null  float64
 11  purpose          119145 non-null  object
 12  addr_state       119145 non-null  object
 13  dti              119145 non-null  float64
 14  open_acc         119145 non-null  int64
 15  revol_bal        119145 non-null  int64
 16  revol_util       119145 non-null  float64
 17  total_acc        119145 non-null  int64
 18  loan_status      119145 non-null  object
dtypes: float64(6), int64(7), object(6)
memory usage: 17.3+ MB

In [6]:
clean_df.isna().sum()

member_id          0
loan_amnt          0
funded_amnt        0
funded_amnt_inv    0
term               0
int_rate           0
installment        0
grade              0
emp_length         0
home_ownership     0
annual_inc         0
purpose            0
addr_state         0
dti                0
open_acc           0
revol_bal          0
revol_util         0
total_acc          0
loan_status        0
dtype: int64

#Spilt Data

In [7]:
data = clean_df.sample(frac=0.001, random_state=12345)
data_unseen = clean_df.drop(data.index)
data.reset_index(drop=True, inplace=True)
data_unseen.reset_index(drop=True, inplace=True)

In [8]:
print(data)
colsToDrop = ["member_id","funded_amnt_inv", "funded_amnt", "revol_bal", "revol_util","total_acc","installment","open_acc"]
data.drop(colsToDrop, axis=1, inplace=True)
data.reset_index(drop=True, inplace=True)
print(data)

     member_id  loan_amnt  funded_amnt  ...  revol_util total_acc  loan_status
0      1657440      16000        16000  ...        56.4        29   Fully Paid
1       696187      12000        12000  ...        45.6        20   Fully Paid
2     10076748      10000        10000  ...        53.5        21   Fully Paid
3       832394      14400        14400  ...        36.2        18   Fully Paid
4     11507942      18250        18250  ...        93.4        10   Fully Paid
..         ...        ...          ...  ...         ...       ...          ...
114    3920299      25675        25675  ...        49.7        29   Fully Paid
115    4147985       3600         3600  ...         0.0        23   Fully Paid
116    1694510       4000         4000  ...        50.1        27   Fully Paid
117     844733       1000         1000  ...        41.1         6   Fully Paid
118    2730864      16000        16000  ...        61.4        30   Fully Paid

[119 rows x 19 columns]
     loan_amnt        term  int_rate  ... addr_state    dti loan_status
0        16000   36 months     12.12  ...         NC  30.60  Fully Paid
1        12000   36 months     13.61  ...         WI  10.32  Fully Paid
2        10000   36 months     11.99  ...         IL  19.11  Fully Paid
3        14400   36 months      7.66  ...         FL  13.10  Fully Paid
4        18250   36 months     18.25  ...         WA   8.54  Fully Paid
..         ...         ...       ...  ...        ...    ...         ...
114      25675   36 months     15.31  ...         CA   5.17  Fully Paid
115       3600   36 months      7.90  ...         OH   0.00  Fully Paid
116       4000   36 months     13.11  ...         IL  22.27  Fully Paid
117       1000   36 months      9.63  ...         TX  18.67  Fully Paid
118      16000   36 months     10.16  ...         OR  14.03  Fully Paid

[119 rows x 11 columns]

In [9]:
data.loc[(data.loan_status == 'Fully Paid'),'loan_status']=0
data.loc[(data.loan_status == 'Default'),'loan_status']=1
data['loan_status']= pd.to_numeric(data['loan_status'])
data.info()
observations = []
for i in range(len(data)):
 observations.append([str(data.values[i,j]) for j in range(11)])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119 entries, 0 to 118
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   loan_amnt       119 non-null    int64
 1   term            119 non-null    object
 2   int_rate        119 non-null    float64
 3   grade           119 non-null    object
 4   emp_length      119 non-null    int64
 5   home_ownership  119 non-null    object
 6   annual_inc      119 non-null    float64
 7   purpose         119 non-null    object
 8   addr_state      119 non-null    object
 9   dti             119 non-null    float64
 10  loan_status     119 non-null    int64
dtypes: float64(3), int64(3), object(5)
memory usage: 10.4+ KB

#Apriori

In [ ]:
association_rules = apriori(observations, min_support=0.0045, min_confidence=0.2, min_lift=3, min_length=2)
association_results = list(association_rules)

#Results

In [ ]:
print(len(association_rules))
print(association_rules[0])